srtFormat = {
    'Elaps' : 'Elpas time:{0}', # This is special header created by OpenTX2SRT
    'Date' : '%Y/%m/%d',    # datetime.srtftime
    'Time' : '%H:%M:%S',    # datetime.srtftime
    '1RSS(dB)' : '{0}dB',
    '2RSS(dB)' : '{0}dB',
    'RQly(%)' : 'RQly:{0}%',
    'RSNR(dB)' : '{0}dB',
    'ANT' : '',
    'RFMD' : '',
    'TPWR(mW)' : '{0}mW',
    'TRSS(dB)' : '{0}dB',
    'TQly(%)' :  '{0}%',
    'TSNR(dB)' : '{0}dB',
    'Ptch(rad)' : '',
    'Roll(rad)' : '',
    'Yaw(rad)' : '',
    'RxBt(V)' : 'VBAT:{0}V',
    'Curr(A)' : '{0}A',
    'Capa(mAh)' : '{0}mAh',
    'Bat_(%)' : '{0}%',
    'FM' : '',
    'GPS' : '',
    'GSpd(kmh)' : 'Speed:{0}Km/h',
    'Hdg(@)' : '',
    'Alt(m)' : 'Alt:{0}m',
    'Sats' : 'Sats:{0}',
    'Rud' : '',
    'Ele' : '',
    'Thr' : '',
    'Ail' : '',
    'SA' : '',
    'SB' : '',
    'SC' : '',
    'SD' : '',
    'SE' : '',
    'SF' : '',
    'LSW' : '',
    'TxBat(V)' : '{0}V'
}